spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/billing_system_db?createDatabaseIfNotExist=true
    username: root
    password: vedant123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    admin-secret: A@athenura321
    manager-secret: M@athenura321
    user:
      name: disable

  mail:
    host: smtp.gmail.com
    port: 587
    username: lokeshkr189@gmail.com
    password: mrki flmz dgql obcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: dwfqsavsx
  api-key: 911959791416542
  api-secret: IbfJ3lzDkXhYonTIAqxAe51tvQ8

logging:
  level:
    org.springframework.security: DEBUG